# Generated by Django 3.0.3 on 2020-03-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20200303_1733"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="tags",),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="accounts.Tag"),
        ),
    ]
